In [120]:
import pandas as pd

y_train = pd.read_csv("/mnt/c/Users/zer0nu11/Documents/workspace/projects/MatModSchool/target_train.csv")
X_train = pd.read_csv("/mnt/c/Users/zer0nu11/Documents/workspace/projects/MatModSchool/data_train.csv")

In [121]:
X_train = X_train.rename(columns={'telemetry_0': 'temp4', 
                        'telemetry_1': 'consumption',
                        'telemetry_2': 'temp1', 
                        'telemetry_3': 'ampere_add',
                        'telemetry_4': 'press_add', 
                        'telemetry_5': 'temp3',
                        'telemetry_6': 'speed', 
                        'telemetry_7': 'press1',
                        'telemetry_8': 'press2', 
                        'telemetry_9': 'temp2',
                        'telemetry_10': 'temp5', 
                        'telemetry_11': 'temp6',
                        'telemetry_12': 'item1', 
                        'telemetry_13': 'item2',
                        'telemetry_14': 'item3', 
                        'telemetry_15': 'item4',})

y_train = y_train.rename(columns={'Ð”Ð°Ñ‚Ð°': 'datetime'})
X_train

,datetime,temp4,consumption,temp1,ampere_add,press_add,temp3,speed,press1,press2,temp2,temp5,temp6,item1,item2,item3,item4
0,2019-03-01 00:01:00,0.737538,0.478367,0.292816,0.644016,0.919471,0.884814,0.754800,0.413295,0.471920,0.677801,0.687535,0.498407,NaN,NaN,NaN,NaN
1,2019-03-01 00:02:00,0.738406,0.478977,0.292816,0.648557,0.919471,0.887129,0.752977,0.413295,0.471920,0.677801,0.688926,0.498407,NaN,NaN,NaN,NaN
2,2019-03-01 00:03:00,0.738985,0.478977,0.292816,0.647164,0.919471,0.887129,0.755444,0.413295,0.471920,0.677801,0.690316,0.498407,NaN,NaN,NaN,NaN
3,2019-03-01 00:04:00,0.739563,0.478977,0.292816,0.636938,0.919471,0.887129,0.754800,0.413295,0.471920,0.678079,0.692820,0.498407,NaN,NaN,NaN,NaN
4,2019-03-01 00:05:00,0.740431,0.477119,0.292816,0.635834,0.919471,0.887707,0.754156,0.413295,0.471920,0.678357,0.695601,0.498407,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319541,2019-10-07 19:54:00,0.716126,0.409256,0.316542,0.604638,0.919214,0.800036,0.741821,0.465318,0.464397,0.728682,0.728682,0.728682,NaN,NaN,NaN,NaN
319542,2019-10-07 19:55:00,0.710918,0.408751,0.316832,0.607323,0.919214,0.800615,0.742358,0.465318,0.464397,0.728682,0.728682,0.728682,NaN,NaN,NaN,NaN
319543,2019-10-07 19:56:00,0.704842,0.409621,0.316832,0.607274,0.919214,0.800615,0.742358,0.465318,0.462082,0.728682,0.728682,0.728682,NaN,NaN,NaN,NaN
319544,2019-10-07 19:57:00,0.697608,0.409000,0.316832,0.611888,0.919214,0.800615,0.742358,0.465318,0.462082,0.728682,0.728682,0.728682,NaN,NaN,NaN,NaN
319545,2019-10-07 19:58:00,0.691243,0.409233,0.316832,0.610702,0.919214,0.800615,0.742358,0.465318,0.462082,0.728682,0.728682,0.728682,NaN,NaN,NaN,NaN

In [123]:
X_train['datetime'] = pd.to_datetime(X_train['datetime'])
y_train['datetime'] = pd.to_datetime(y_train['datetime'])

import numpy as np

X_train = X_train.drop(X_train[X_train['datetime'] < y_train['datetime'][0]].index)
X_train = X_train.drop(X_train[X_train["datetime"] > y_train['datetime'].iloc[-1]].index)
X_train.head()

X_train = X_train.fillna(X_train.iloc[:, X_train.columns.get_loc('datetime')+1:].mean())
X_train = X_train.drop(X_train[X_train.duplicated()].index)
y_train = y_train.drop(y_train[y_train.duplicated()].index)

# X_train.reset_index(drop=True, inplace=True)

# X_train = X_train[X_train['datetime'].isin(y_train['datetime'])]
# X_train['datetime'] = X_train['datetime'].astype(int)
# X_train.to_csv("for_test.csv", index=False)
# X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1772 entries, 18390 to 319487
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     1772 non-null   int64
 1   temp4        1772 non-null   float64
 2   consumption  1772 non-null   float64
 3   temp1        1772 non-null   float64
 4   ampere_add   1772 non-null   float64
 5   press_add    1772 non-null   float64
 6   temp3        1772 non-null   float64
 7   speed        1772 non-null   float64
 8   press1       1772 non-null   float64
 9   press2       1772 non-null   float64
 10  temp2        1772 non-null   float64
 11  temp5        1772 non-null   float64
 12  temp6        1772 non-null   float64
 13  item1        1772 non-null   float64
 14  item2        1772 non-null   float64
 15  item3        1772 non-null   float64
 16  item4        1772 non-null   float64
dtypes: float64(16), int64(1)
memory usage: 249.2 KB

In [111]:
def getLinearSplice(value_one, value_two, count):
    global expanded_target

    # time_distance = (time_finish - time_start) / 60
    koef = (value_two - value_one) / count
    
    # print((point_two - point_one))
    # print(point_two.timestamp())
    # print(time_distance)

    expanded_target.append(value_one)
    # print(value_one)
    # print(expanded_target)

    target = value_one
    for i in range(int(count)):
        target += koef
        # print(target)
        expanded_target.append(target)
    # expanded_target.append(value_two)
    return

In [112]:
# X_train['datetime'].astype(int)
from datetime import datetime

# X_train['datetime'].loc[X_train['datetime'] == y_train['datetime'].iloc[1]].astype(int)
# y_train['target'].iloc[i-1]
# int((datetime.strptime(str(y_train['datetime'][1]), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(y_train['datetime'][0]), "%Y-%m-%d %H:%M:%S")).total_seconds() / 60)
# a = X_train['datetime'].loc[X_train['datetime'] == y_train['datetime'].iloc[i-1]].index[0]
# a
# print(pd.to_numeric(a))
# X_train['datetime'][y_train['datetime'].loc[y_train['datetime'].iloc[1]]]
print(X_train['datetime'].loc[X_train['datetime'] == y_train['datetime'].iloc[0]].index[0])
X_train['datetime'].loc[X_train['datetime'] == y_train['datetime'].iloc[1]].index[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
expanded_target = list()
for i in range(1, len(y_train)-1):
    index_one = (X_train['datetime'].loc[X_train['datetime'] == y_train['datetime'].iloc[i-1]].index[0])
    index_two = (X_train['datetime'].loc[X_train['datetime'] == y_train['datetime'].iloc[i]].index[0])
    # X_train['datetime'][y_train['datetime'].loc[y_train['datetime'].iloc[i-1]]]
    # print(i)
    getLinearSplice(y_train['target'].iloc[i-1],
                    y_train['target'].iloc[i],
                    # int((datetime.strptime(str(y_train['datetime'][index_two]), "%Y-%m-%d %H:%M:%S") - \
                    #      datetime.strptime(str(y_train['datetime'][index_one]), "%Y-%m-%d %H:%M:%S")).total_seconds() / 60)
                    index_two - index_one
    )
    
y_train_expanded = pd.DataFrame({
    # 'datetime': X_train['datetime'],
    'target': expanded_target
})

# getLinearSplice(y_train['datetime'].iloc[0].timestamp(), 
#                 y_train['datetime'].iloc[1].timestamp(),
#                 y_train['target'].iloc[0],
#                 y_train['target'].iloc[1])

# expanded_target = pd.Series(expanded_target, dtype="float64")
# expanded_target

# y_train_expanded = pd.DataFrame({
#     # 'datetime': X_train['datetime'],
#     'target': expanded_target
# })

# y_train_expanded[y_train_expanded.duplicated()]
y_train_expanded

          target
0       0.123711
1       0.124527
2       0.125344
3       0.126160
4       0.126976
...          ...
302863  0.179983
302864  0.180090
302865  0.180198
302866  0.180305
302867  0.180412

[302868 rows x 1 columns]

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 299700 entries, 18390 to 319545
Data columns (total 17 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   datetime     299700 non-null  datetime64[ns]
 1   temp4        299700 non-null  float64
 2   consumption  299700 non-null  float64
 3   temp1        299700 non-null  float64
 4   ampere_add   299700 non-null  float64
 5   press_add    299700 non-null  float64
 6   temp3        299700 non-null  float64
 7   speed        299700 non-null  float64
 8   press1       299700 non-null  float64
 9   press2       299700 non-null  float64
 10  temp2        299700 non-null  float64
 11  temp5        299700 non-null  float64
 12  temp6        299700 non-null  float64
 13  item1        299700 non-null  float64
 14  item2        299700 non-null  float64
 15  item3        299700 non-null  float64
 16  item4        299700 non-null  float64
dtypes: datetime64[ns](1), float64(16)
memory usage: 41.2 MB